[tool.poetry]
name = "genai-playground"
package-mode = false

[tool.poetry.dependencies]
python = "^3.12"
generative-ai-hub-sdk = "^1.2.2"


[tool.poetry.group.dev.dependencies]
ipykernel = "^6.29.3"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
